[[redirects]]
  from = "https://diplock.tk/contest/*"
  to = "https://diplock.app.link/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/it"
  status = 301
  force = true
  conditions = {Country = ["IT"]}

[[redirects]]
  from = "/*"
  to = "/en/index.html"
  status = 200